class_name CCU02StardustBoost
extends Upgrade
## Unlocks speedy stardust generation

## Max level of this upgrade
var max_level : int = 5

## Load data from save
func _init() -> void:
	level = Game.ref.data.cc_upgrades.upgrade_02_stardust_boost_level
	title = "Stardust Generator Efficiency"
	base_cost = 1
	level_exponential = 1.5
	cost = 1

## Abstract method, must be overwritten.[br]
## Return the description of the upgrade based on current cost / effects
func description() -> String:
	var text : String = "Increases the amount of Stardust generated by the Universe Core."
	text += "\n[b]Effect:[/b] +1 Stardust / second"
	
	if level < max_level:
		text += "\n[b]Cost:[/b] %s Consciousness Core" %cost
		
	return text

## Returns boolean for whether the player can afford the upgrade or not
func can_afford() -> bool:
	if level >= max_level:
		return false
	
	if Game.ref.data.consciousness_core >= cost:
		return true
		
	return false

## Consume stardust + level up
func level_up() -> void:
	if level >= max_level:
		return
		
	var error : Error = HandlerConsciousnessCore.ref.consume_consciousness_core(cost)
	
	if error:
		return
		
	level += 1
	Game.ref.data.cc_upgrades.upgrade_02_stardust_boost_level += 1
	
	leveled_up.emit()
	HandlerCCUpgrades.ref.upgrade_leveled_up.emit(self)
